loc_Appconfig_Username = "xpath = //input[@id='UserName']"
loc_Appconfig_Password = "xpath = //input[@id='Password']"
loc_Appconfig_Login =    "id=submit-button"
loc_Appconfig_LogOff=    "xpath=//li[@id='link-disconnect']"
loc_Appconfig_MainMenu=    "xpath=//ul[@id='main-menu']"

# Left menu
loc_Appconfig_LeftPanel_Home=     "xpath=//li[@id='link-home']/a"
loc_Appconfig_LeftPanel_agenda_exception=     "xpath=//li[@id='link-AgendaException']/a"
loc_Appconfig_LeftPanel_alarm_maintenance=     "xpath=//li[@id='link-alarmMaintenances']/a"
loc_Appconfig_LeftPanel_auditlogs=     "xpath=//li[@id='link-auditlogs']/a"
loc_Appconfig_LeftPanel_bundling=    "xpath=//li[@id='link-bundling']/a"
loc_Appconfig_LeftPanel_calendar=                   "xpath=//li[@id='link-calendar']/a"
loc_Appconfig_LeftPanel_conditions=     "xpath=//li[@id='link-condition']/a"
loc_Appconfig_LeftPanel_configuration_manager=     "xpath=//li[@id='link-ConfigurationManager']/a"
loc_Appconfig_LeftPanel_copy_config=     "xpath=//li[@id='link-copyConfig']/a"
loc_Appconfig_LeftPanel_create_new_personnel=       "xpath=//li[@id='link-personnel']/a"
loc_Appconfig_LeftPanel_damage_assessment=     "xpath=//li[@id='link-da']/a"
loc_Appconfig_LeftPanel_disposal_codes=     "xpath=//li[@id='link-DisposalCode']/a"
loc_Appconfig_LeftPanel_error_handling=     "xpath=//li[@id='link-error-handling']/a"
loc_Appconfig_LeftPanel_esp_configuration=     "xpath=//li[@id='link-esp-configuration']/a"
loc_Appconfig_LeftPanel_esp_schedule=              "xpath=//li[@id='link-esp-schedule']/a"
loc_Appconfig_LeftPanel_job_field_lock_maintenance=     "xpath=//li[@id='link-FieldLock']/a"
loc_Appconfig_LeftPanel_job_report_selections=     "xpath=//li[@id='link-JobReportSelection']/a"   
loc_Appconfig_LeftPanel_material_maintenace=     "xpath=//li[@id='link-material']/a"
loc_Appconfig_LeftPanel_me_activity_job_types=     "xpath=//li[@id='link-ME-ActivityJobType']/a"
loc_Appconfig_LeftPanel_me_activity_type=     "xpath=//li[@id='link-ME-ActivityType']/a"
loc_Appconfig_LeftPanel_me_button_action=     "xpath=//li[@id='link-ME-ButtonAction']/a"
loc_Appconfig_LeftPanel_me_data_source=     "xpath=//li[@id='link-ME-DataSource']/a"
loc_Appconfig_LeftPanel_priority=     "xpath=//li[@id='link-Priority']/a"
loc_Appconfig_LeftPanel_query_builder=     "xpath=//li[@id='link-querybuilder']/a"
loc_Appconfig_LeftPanel_reason_exception_color=     "xpath=//li[@id='link-reasonexcpclr']/a"
loc_Appconfig_LeftPanel_resource_work_optimization=    "xpath=//li[@id='link-rwo']/a" 
loc_Appconfig_SafetyMessage=    "xpath=//li[@id='link-safetyms']/a"
loc_Appconfig_LeftPanel_same_premise=               "xpath=//li[@id='link-samePremise']/a"
loc_Appconfig_LeftPanel_status_group_maintenance=   "xpath=//li[@id='link-statusgr']/a"
loc_Appconfig_LeftPanel_test_maintenance=     "xpath=//li[@id='link-test']/a"
loc_Appconfig_LeftPanel_timesheet_configuration=    "xpath=//li[@id='link-ts-configuration']/a"


# loc_Appconfig_SafetyMessage=    "xpath=//li[contains(text(),'SAFE.MS.')]"

#Page items
loc_Appconfig_AlarmMaintenance_AlarmConfig_Name=    "xpath=//input[@id='CurrentAlarmEventRow_AlarmName']"
loc_Appconfig_AuditLog_ModificationDate=    "xpath=//div[@class='pq-from-div']//input[@name='ModDate']"
loc_Appconfig_SafetyMessage_Message=    "xpath=//textarea[@id='CurrentSafetyMessageRow_Message']"
loc_Appconfig_Bundling_BundlingDefinition_Agency=    "xpath=//select[@id='CurrentRow_AgencyId']"
loc_Appconfig_Calendar_Holiday_Name=    "xpath=//input[@id='CurrentHolidayRow_Name']"
loc_Appconfig_Conditions_ConditionType=    "xpath=//select[@id='CurrentCondition_TypeId']"
loc_Appconfig_CopyConfig_CopyConfig_SourceDatabase=    "xpath=//select[@id='SourceDBNameList']"
loc_Appconfig_ConfigManager_Application=    "xpath=//select[@id='applicationSelect']"
loc_Appconfig_DamageAssessment_DamageTypes_Name=    "xpath=//input[@id='damagetype-field-name']"
loc_Appconfig_MaterialMaint_MaterialCategories_Name=    "xpath=//input[@id='MaterialCategoryName']"
loc_Appconfig_RWO_Maintenance_ProfileList=    "xpath=//select[@id='RWOProfileList']"
loc_Appconfig_CreateNewPersonnel_Agency=    "xpath=//select[@id='AgencyCode']"
loc_Appconfig_QueryBuilder_Form=    "xpath=//select[@id='Context_FormId']"
loc_Appconfig_TestMaint_NumberPropertyID=    "xpath=//input[@id='NumberProperty']"
loc_Appconfig_SamePremise_AgenciesGroupDefinition_Name=    "xpath=//input[@id='CurrentGroupDefinitionRow_Name']"
loc_Appconfig_SafetyMessage_CommunicationGroups=    "xpath=//select[@id='CurrentSafetyMessageRow_PcommGroup']"
loc_Appconfig_StatusGroupMaintenance_Statuses_StatusGroup=    "xpath=//input[@id='StatusCode']"
loc_Appconfig_ReasonExceptionColor_Name=    "xpath=//select[@id='SelectedVtbName']"
loc_Appconfig_JobFieldLockMaintenance_AgencyCode=    "xpath=//select[@id='CurrentFieldLockRow_AgencyCode']"
loc_Appconfig_JobReportSelections_AgencyCode=    "xpath=//select[@id='CurrentJobReportSelectionRow_AgencyCode']"
loc_Appconfig_DisposalCode_AgencyCode=    "xpath=//select[@id='CurrentDisposalCodeRow_AgencyCode']"
loc_Appconfig_EspConfig_AgencyCode=    "xpath=//select[@id='EspFilters_AgencyCode']"
loc_Appconfig_EspSchedule_Schedule_AgencyCode=    "xpath=//select[@id='CurrentRow_AgencyCode']"
loc_Appconfig_TimesheetConfiguration_General_Personnelmode=    "xpath=//input[@value='COMPLETE']"
loc_Appconfig_ErrHandling_ErrList_TransanctionID=    "xpath=//input[@id='CurrentRow_ID']"
loc_Appconfig_Priority_SystemPriority=    "xpath=//input[@id='SystemPrioritiesRow_Priority']"
loc_Appconfig_MeActivityType_ActivityType_ActivityName=    "xpath=//input[@id='CurrentActivityTypeRow_Name']"
loc_Appconfig_MeActivityJobType_ActivityType_ButtonCode=    "xpath=//select[@id='CurrentActivityJobTypeRow_ButtonCode']"
loc_Appconfig_MeDataSource_AttributeName=    "xpath=//input[@id='CurrentDataSourceRow_AttributeName']"
loc_Appconfig_ButtonActions_ButtonCode=    "xpath=//select[@id='CurrentButtonActionRow_ButtonCode']"
loc_Appconfig_AgendaExcep_AgencyCode=    "xpath=//select[@id='agencySelect']"








